# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-14 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('desc', models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u8bfe\u7a0b\u8be6\u60c5')),
                ('degree', models.CharField(choices=[('low', '\u4f4e\u7ea7'), ('middle', '\u4e2d\u7ea7'), ('high', '\u9ad8\u7ea7')], max_length=6, verbose_name='\u96be\u5ea6')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('learn_time', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u4ee5\u5206\u949f\u8ba1\u7b97\uff09')),
                ('click', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u7f29\u7565\u56fe')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='\u8bfe\u7a0b\u673a\u6784')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u8bfe\u7a0b\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u8d44\u6e90\u540d\u79f0')),
                ('download', models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='\u8d44\u6e90\u4e0b\u8f7d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8d44\u6e90',
                'verbose_name_plural': '\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Lession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_times', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f')),
                ('name', models.CharField(max_length=50, verbose_name='\u7ae0\u8282\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282\u4fe1\u606f',
                'verbose_name_plural': '\u7ae0\u8282\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('learn_times', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f')),
                ('url', models.URLField(max_length=100, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lession', verbose_name='\u6240\u5c5e\u7ae0\u8282')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u8868',
                'verbose_name_plural': '\u89c6\u9891\u8868',
            },
        ),
    ]
