# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-15 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='lesson',
            new_name='lession',
        ),
    ]
