# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-20 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='type',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='pxjg', max_length=10, verbose_name='\u673a\u6784\u7c7b\u578b'),
        ),
    ]
